### ISSUE TITLE
Versions and branches on github

### ISSUE THREAD

**Issue by cristinarc** [ocpi/ocpi#86] opened 2016-02-15 10:18 UTC
There will be maximum two active branches: `master` and the one that will be used for the next Document with textual fixes. 
1.) The most recent state of the spec, the "bleeding edge", is in the `master` branch.

2A.) Just master branch is active:
In this scenario we are just working on the next release (there are not changes to be one in previous ones)
- When we have collected all changes for a new version, a new branch is created and named like the new release/document version (e.g. `v2.1` or `D2`) with the current version of `master`.

2B.) The `master` and the branch with document fixes are active:
In this scenario we are working on changes for the next release and in an already done release (already existing branch)
- ​_New release_​: all changes that will take part of the next release will be done directly just in `master` branch
- ​_Fixes old release_​: the changes that need to be taken into account for the older release will be done first in the branch (e.g. `v2.0`/`D1`) and then ​_cherry picked_​ into master (carefully). Therefore this branch will stay in the past, and won't have the changes that are done in `master`, but `master` will _always_​ have all its changes merged.

3.) The PDFs are created from the corresponding branch, never from master

​_Note that_​: rebases won’t be done, just merges

**Comment by simonphilips** [comment] 2016-03-18 12:10
To answer some questions on how to contribute and report issues, it might be best to add a small document to the repository. It should probably go into CONTRIBUTING.md

It would probably be good to have some feedback from @RobertdeLeeuw-IHomer as well.

# How to contribute

## Spelling mistakes

Spelling mistakes are errors that do not change the intended meaning of the documentation. When in doubt about the intention, create a Github issue instead, otherwise they can be fixed in the master branch or by making a pull request if you do not have write access to the master branch.

## Unclarities and documentation errors

Create a Github issue, provide a link to the section and document, and describe what you think is unclear or wrong and preferably propose a way to fix it.

## Protocol errors and protocol change requests

For errors that are part of the protocol design and for change requests to the protocol, a Github issue must be created containing the following information:

1. Identification of the part of the protocol that needs a change
2. One or more detailed use-case explaining why the protocol is misbehaving ("context and steps to reproduce") or what situation the change must solve.
3. An initial proposal to fix or change the protocol. This may help explaining the use-case as well. If you intend to break backward compatibility, then also provide a motivation for this particular solution.

**Comment by poohsen** [comment] 2016-03-21 12:22
> When we have collected all changes for a new version, a new branch is created and named like the new release/document version (e.g. v2.1 or D2)

**Closed** 2018-11-21 17:19 UTC
