### ISSUE TITLE
Add energy qualification to EVSE

### ISSUE THREAD

**Issue by LeonHuijsdens** [ocpi/ocpi#33] opened 2015-07-17 06:20 UTC
I propose that we add an energy qualification attribute to the EVSE's.  It allows for eMSPs and drivers to select (for instance) green energy stations.

It could look as follows  (don't mind the poor JSON notation)

{ "Energy Classification" :
           { "Green" : 60
                { "Unspecified" : 0,
                  "Wind" : 80,
                  "Bio" : 0,
                  "Solar" : 20,
               }
             "Grey" : 40
         }
}

**Comment by rutgerplantenga** [comment] 2015-07-17 06:56
Fully agree with that - as also expressed in
https://github.com/ocpi/ocpi/issues/16 ;-)

Let's merge these issues.


*Rutger Plantenga*
+316 2907 6069

Keizersgracht 585
1017 DR Amsterdam

Postbus 3966
1001 AT Amsterdam

**Comment by LeonHuijsdens** [comment] 2015-07-17 07:36
Ok ?

Verstuurd vanaf mijn iPhone

Op 17 jul. 2015 om 08:57 heeft "Rutger Plantenga" <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Fully agree with that - as also expressed in
https://github.com/ocpi/ocpi/issues/16 ;-)

Let's merge these issues.


*Rutger Plantenga*
+316 2907 6069

Keizersgracht 585
1017 DR Amsterdam

Postbus 3966
1001 AT Amsterdam


On Fri, Jul 17, 2015 at 8:20 AM, LeonHuijsdens <notifications@github.com<mailto:notifications@github.com>>
wrote:

> I propose that we add an energy qualification attribute to the EVSE's. It
> allows for eMSPs and drivers to select (for instance) green energy stations.
>
> It could look as follows (don't mind the poor JSON notation)
>
> { "Energy Classification" :
> { "Green" : 60
> { "Unspecified" : 0,
> "Wind" : 80,
> "Bio" : 0,
> "Solar" : 20,
> }
> "Grey" : 40
> }
> }
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/ocpi/ocpi/issues/33>.
>

-

**Comment by simonschllng** [comment] 2015-07-17 13:44
When selling electric power to customers it is mandatory to show the sources of the power. As far as I know no eMSP nor CPO is doing this at the moment. Based on the current market structure the operator would need to provide this information. As they will not be able to display it directly, the eMSP or Navigation Provider would need to display it on behalf.
This would also imply that the information is provided based on the used tariff. It might not the same for all charging stations of one operator and also not for all customers at one station. Especially in the smart charging usecase.

#### References:
 * Information in Wikipedia: [en](https://en.wikipedia.org/wiki/Fuel_mix_disclosure) | [nl](https://nl.wikipedia.org/wiki/Stroometikettering) | [de](https://de.wikipedia.org/wiki/Stromkennzeichnung)
 * EC Directive 2003/54/EC establishing Fuel mix disclosure: [en](http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2009:211:0055:0093:EN:PDF) | [de](http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2009:211:0055:0093:DE:PDF) | [nl](http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2009:211:0055:0093:NL:PDF)
 * [Leitfaden Stromkennzeichnung](https://www.bdew.de/bdew.nsf/id/DE_Datenplattform_Stromkennzeichnung/$file/2010%2003%2015_Leitfaden%20SK_bis%20BJ2009_Endfassung%20mit%20Anpassungen.pdf) (in german) is a gide how to apply the law which implements EC Directive 2003/54/EC.

#### Example
This is how it would need to be shown when the directive is applied. We would need all this data in the protocol, except for the comparison on the right hand side what can be derived from other sources.
![Example](https://www.eon.de/content/dam/eon-de/Images/privatkunden/EDG_SKZ_2013_web.gif)

**Comment by rutgerplantenga** [comment] 2015-07-17 15:22
Seeing this I would suggest that we take a practical end-user approach
here, not a completely Directive-conform one.

I'd expect the following common scenarios:
- Users that want to charge only at chargepoints with green energy (where
one can argue about what's green exactly).
- Users that don't mind so much but do want to avoid using any nuclear
energy.
- Users that don't mind at all.

If we'd just allow the EVSE's energy-mix to be communicated with following
categories (copied from the wikipedia examples):
% biomass
% coal
% natural gas
% nuclear
% other
% solar
% water
% wind

then we should be able to cover all these scenarios (and more), while
keeping the solution quite straightforward. PS. I don't like the 'Other' in
there but I see that it's being used so I suppose we'd better include it.

Rutger



*Rutger Plantenga*
+316 2907 6069

Keizersgracht 585
1017 DR Amsterdam

Postbus 3966
1001 AT Amsterdam

**Comment by poohsen** [comment] 2015-07-31 09:03
I improved Leon's example a little. 
- "unspecified" is implicit: it's the percentage between the sum of the percentages given explicitly and 100%

Energy classification:
```
{  
   "green":60,
   "green_breakdown":{  
      "wind":60,
      "bio":0,
      "solar":20
   },
   "gray":40,
   "gray_breakdown":{  
      "nuclear":100
   }
}
```

**Comment by simonschllng** [comment] 2016-02-29 09:50
duplicate of #81

**Comment by simonschllng** [comment] 2016-02-29 09:50
duplicate of #81

**Closed by simonschllng** 2016-02-29 09:50 UTC
Labels: enhancement
