### ISSUE TITLE
Is SignedData url really case-insensitive?

### ISSUE THREAD

**Issue by lantw44** [ocpi/ocpi#361] opened 2021-08-27 09:09 UTC
OCPI defines `URL` type as a case-sensitive `string(255)` following the URL format, but the `url` field of `SignedData` class uses `CiString(512)`. Shouldn't it use `string(512)` because URLs are case-sensitive?

**Comment by frankhommers** [comment] 2021-09-02 17:05
Dupe of or at least related to https://github.com/ocpi/ocpi/issues/293 ?

**Comment by lantw44** [comment] 2021-09-06 08:12
It is related to https://github.com/ocpi/ocpi/issues/293 but it is not a duplicate of it. https://github.com/ocpi/ocpi/issues/293 resolves the problem for `public_key`, `plain_data`, `signed_data` fields but not `url` field.

**Comment by RobertdeLeeuw-IHomer** [comment] 2021-09-07 15:03
You are right, thanks for reporting this.

**Closed** 2021-09-13 17:48 UTC
