### ISSUE TITLE
Change country code from ISO 3166-1 alpha-3 code to alpha-2

### ISSUE THREAD

**Issue by GregoireWulliamoz** [ocpi/ocpi#397] opened 2022-06-29 13:11 UTC
Currently country code ISO 3166-1 alpha-3 is only used in Location.Country and CdrLocation.Country while all other country codes are using ISO 3166-1 alpha-2.
It would be nice to standardize the use of a country code.

**Comment by mbayings** [comment] 2022-06-29 15:18
To be honest I have no idea why this is done. We use it this way from the beginning. So far no one had an issue with it, so I think that is why it is as it is. From visibility perspective, 3 characters is a bit more clear than 2, but I have no idea if that was the reason when we made the first specs 8 years ago.

ISO 3166-1 alpha-3 is also a standard.
We can of course decide to go to the 2 character standard, but that might give big issues with current implementations. 
So what I am wondering: what is the current problem with it or what problems are caused by current situation? (besides that it can be nice to have it all the same way).

**Comment by GregoireWulliamoz** [comment] 2022-06-30 04:57
There is no problem, it is just about consistency.

**Comment by reinierl** [comment] 2022-06-30 11:10
As with your other issue, I'm closing this one and replacing it with one in the OCPI 3.x project: https://github.com/ocpi/ocpi-3/issues/139

**Closed by reinierl** 2022-06-30 11:10 UTC
