### ISSUE TITLE
Energy qualification to EVSE (15.)

### ISSUE THREAD

**Issue by cristinarc** [ocpi/ocpi#81] opened 2016-02-05 10:21 UTC
Is there an international standard?

**Comment by Mygyll** [comment] 2016-02-05 11:04
List from Greenflux:

**1.	Green**
a.	Wind
b.	Solar
c.	Wave
d.	Geothermal
e.	Hydro
f.	Biomass
**2.	Grey**
**3.	Nuclear**

**Comment by simonschllng** [comment] 2016-02-09 12:34
This is a duplicate of #33. There I did also give reference to standards and laws.

**Comment by simonphilips** [comment] 2016-02-12 14:33
From the directive:

## Kernkraft:
Kernkraftwerke, Siedewasserreaktor, Druckwasserreaktor, Uran, Thorium. 

## Fossile und sonstige Energieträger:
Kohlekraftwerke, Gaskraftwerke, Mischfeuerungsanlagen, Pumpspeicher ohne natürlichen Zufluss, Heizkraftwerke, KWK-Anlagen, Braunkohle, Steinkohle, Erdgas, Heizöl, Synthesegase, Grubengas, Methanol, GuD-Kraftwerk, Brennstoffzelle Erdgas, BHKW Erdgas, Hybridkraftwerke (IGCC-Anlagen), Kombikraftwerke. 

## Erneuerbare Energien:
 Erneuerbare Energien sind Wasserkraft einschließlich der Wellen-, Gezeiten-, Salzgradienten- und Strömungsenergie, Windenergie, solare Strahlungsenergie, Geothermie, Energie aus Biomasse einschließlich Biogas, Deponiegas und Klärgas sowie aus dem biologisch abbaubaren Anteil (per Konvention 50%) von Abfällen aus Haushalten und Industrie.

**Comment by simonschllng** [comment] 2016-02-12 14:36
_from the face 2 face meeting:_

Agreement/solution:

 * We add the resource categories from the directive as one optional
   object to the location.
 * We add the pollution categories as well, also optional.

**Comment by simonschllng** [comment] 2016-02-29 11:24
After some discussions on the topic, I would like to suggest the following solution:

 * Add an optional object `energy_mix` to the location.
   - We agreed on adding it to the EVSE-level, which just creates redundancy and makes it harder to present the data to the user.
   - I do not think, that there are different energy sources/contracts per EVSE. If so, the operator should create multiple locations.
   - We could add this object optionally to the tariff, which then would override location specific data.
 * The `energy_mix` object contains multiple elements:
   - mandatory Boolean `is_green_energy`: True if 100% from regenerative sources. (CO2 and nuclear waste is zero)
   - optional List `energy_sources`: Key-value pairs (enum + percentage) of energy sources.
   - optional List `environmental_impact`: Key-value pairs (enum + percentage) of energy waste and CO2, etc.
   - optional String `supplier_name`: Name of the energy supplier,
   - optional String `energy_tariff`: Name of the supplier's tariff. These fields can be used to look-up energy qualification or to show it directly to the customer (for well-known brands like Greenpeace Energy, etc.)

This all is informative in only needed for customer information. We don't need it in the CDR or elsewhere.

See: Commit 9c5eec2

**Comment by Mygyll** [comment] 2016-03-10 09:34
I agree of putting the `energy_mix` object at `Location` instead of `EVSE`. I have no objection of putting this object optional in the `tariff` object.
The `energy_mix` object is looking good this way.

**Comment by RobertdeLeeuw-IHomer** [comment] 2016-03-24 16:50
merged and fixed.

**Closed by RobertdeLeeuw-IHomer** 2016-03-24 16:50 UTC
Labels: 2.1, discuss in meeting, duplicate
